// We give authors the control to override the default heading id generated by slugify
// This function extracts the custom id from the heading node if it exists

import type { Node } from 'unist'

export const extractHeadingFromHeadingNode = (node: Node) => {
  // eg # test {{ id: 'my-heading' }}
  // This is for remapping the hash to the custom id
  const id =
    ('children' in node &&
      Array.isArray(node.children) &&
      (node?.children
        ?.find(
          (child: unknown) =>
            typeof child === 'object' && child !== null && 'type' in child && child?.type === 'mdxTextExpression',
        )
        ?.data?.estree?.body?.find(
          (child: unknown) =>
            typeof child === 'object' && child !== null && 'type' in child && child?.type === 'ExpressionStatement',
        )
        ?.expression?.properties?.find(
          (prop: unknown) =>
            typeof prop === 'object' &&
            prop !== null &&
            'key' in prop &&
            typeof prop.key === 'object' &&
            prop.key !== null &&
            'name' in prop.key &&
            prop.key.name === 'id',
        )?.value?.value as string | undefined)) ||
    undefined

  return id
}
