name: Run Migration Mapping Check

permissions:
  contents: read

on:
  push:
    paths:
      - 'proposal-mapping.json'
      - 'proposal.md'
      - 'scripts/migration-assistant/map-content.ts'
      - 'docs/**'

jobs:
  migration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm i
      - run: npm run migration:generate-manifest
      - run: npm run migration:map-content
