name: Redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - core-1
    paths:
      - 'docs/**'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger redeploy
        run: |
          curl -X POST ${{ secrets.WEBSITE_DEPLOY_HOOK }}
      - name: Trigger search reindex
        run: |
          curl -X POST ${{ secrets.SEARCH_INDEX_DEPLOY_HOOK }}
