name: Redeploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - core-1
    paths:
      - 'docs/**'

jobs:
  redeploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_HOOK: ${{ github.ref == 'refs/heads/main' && secrets.WEBSITE_DEPLOY_HOOK || secrets.WEBSITE_DEPLOY_HOOK_CORE_1 }}
    steps:
      - name: Trigger redeploy
        run: |
          curl -X POST ${{ env.DEPLOY_HOOK }}
