name: Generate Typedocs

on:
  workflow_dispatch:

jobs:
  typedoc:
    permissions:
      contents: write
      pull-requests: write

    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: current_date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          path: clerk-docs
          fetch-depth: 1
          show-progress: false

      - name: Checkout clerk/javascript
        uses: actions/checkout@v4
        with:
          repository: clerk/javascript
          path: clerk-javascript
          fetch-depth: 1
          show-progress: false

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Should be the same as clerk/javascript
          run_install: false

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # Should be similar to clerk/javascript
          cache: 'pnpm'
          cache-dependency-path: 'clerk-javascript/pnpm-lock.yaml'

      - name: Install dependencies and build
        working-directory: ./clerk-javascript
        run: |
          pnpm install
          pnpm typedoc:generate

      - name: Copy docs to main repo
        run: |
          # Copy the generated docs to the root of the main repo
          cp -r ./clerk-javascript/.typedoc/docs ./clerk-docs/clerk-typedoc

      - name: Configure Git
        working-directory: ./clerk-docs
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Commit and push changes
        working-directory: ./clerk-docs
        run: |
          git checkout -b typedoc-${{ env.date }}
          git add .
          git commit -m "initial"
          git push origin typedoc-${{ env.date }}

      - name: Create Pull Request
        working-directory: ./clerk-docs
        run: gh pr create --base main --head typedoc-${{ env.date }} --title "[ci] Update Typedoc (${{ env.date }})" --body "Auto-generated PR to update Typedoc documentation from clerk/javascript"
        env:
          GH_TOKEN: ${{ github.token }}
